# Custom Language File for Launcher Customizer
# Based on Helios Launcher by dscalzi

[ejs.app]
title = "TECNILAND Nexus"

[ejs.landing]
mediaGitHubURL = "https://github.com/Ppkeash"
mediaXURL = "#"
mediaInstagramURL = "https://www.instagram.com/ppzek_sh/"
mediaYouTubeURL = "https://www.youtube.com/@lil_kysh"
mediaDiscordURL = "https://discord.gg/53T4Tzrea3"

[ejs.settings]
# Original: https://github.com/dscalzi/HeliosLauncher
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BIENVENIDO A TECNILAND NEXUS"
welcomeDescription = "Este launcher fue creado para ofrecer una experiencia clara, estable y hecha a medida. A diferencia de otros launchers genéricos, TECNILAND integra todo en un solo lugar: acceso simplificado, configuración optimizada, actualizaciones controladas y una interfaz pensada para que solo tengas que jugar. Aquí no descargas mods al azar ni ajustas cosas técnicas; el launcher se encarga de mantener todo sincronizado para que entres al juego sin complicaciones. Es la forma más directa y confiable de vivir la experiencia TECNILAND."
welcomeDescCTA = "Diseñado para la forma en que TECNILAND se vive."
